print "Volume Name: stripe-four"
print "Type: Stripe"
print "Volume ID: 9758af5e-1eb9-4c3e-b864-a20bdfb9b043"
print "Status: Started"
print "Number of Bricks: 1 x 4 = 4"
print "Transport-type: tcp"
print "Bricks:"
print "Brick1: node-a1:/data/four"
print "Brick2: node-a2:/data/four"
print "Brick3: node-b1:/data/four"
print "Brick4: node-b2:/data/four"
print ""
print "Volume Name: dist"
print "Type: Distribute"
print "Volume ID: ac397804-8a31-4fad-a675-21ca60213ec4"
print "Status: Started"
print "Number of Bricks: 4"
print "Transport-type: tcp"
print "Bricks:"
print "Brick1: node-a1:/data/dist"
print "Brick2: node-a2:/data/dist"
print "Brick3: node-b1:/data/dist"
print "Brick4: node-b2:/data/dist"
print ""
print "Volume Name: stripe"
print "Type: Distributed-Stripe"
print "Volume ID: 4193b988-6b16-4150-8c34-323baf063012"
print "Status: Started"
print "Number of Bricks: 2 x 2 = 4"
print "Transport-type: tcp"
print "Bricks:"
print "Brick1: node-a1:/data/stripe"
print "Brick2: node-a2:/data/stripe"
print "Brick3: node-b1:/data/stripe"
print "Brick4: node-b2:/data/stripe"
