print "Status of volume: stripe"
print "------------------------------------------------------------------------------"
print "Brick                : Brick node-a1:/data/stripe"
print "Port                 : 24010"
print "Online               : Y"
print "Pid                  : 1357"
print "File System          : ext4"
print "Device               : /dev/sda5"
print "Mount Options        : rw"
print "Inode Size           : 256"
print "Disk Space Free      : 134.8GB"
print "Total Disk Space     : 135.0GB"
print "Inode Count          : 8994816"
print "Free Inodes          : 8994733"
print "------------------------------------------------------------------------------"
print "Brick                : Brick node-b1:/data/stripe"
print "Port                 : 24010"
print "Online               : Y"
print "Pid                  : 1318"
print "File System          : ext4"
print "Device               : /dev/sda5"
print "Mount Options        : rw"
print "Inode Size           : 256"
print "Disk Space Free      : 131.4GB"
print "Total Disk Space     : 135.0GB"
print "Inode Count          : 8994816"
print "Free Inodes          : 8955939"
print "------------------------------------------------------------------------------"
print "Brick                : Brick node-b2:/data/stripe"
print "Port                 : 24010"
print "Online               : Y"
print "Pid                  : 1331"
print "File System          : ext4"
print "Device               : /dev/sda5"
print "Mount Options        : rw"
print "Inode Size           : 256"
print "Disk Space Free      : 134.7GB"
print "Total Disk Space     : 135.0GB"
print "Inode Count          : 8994816"
print "Free Inodes          : 8959974"
